/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.govt_login;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;



/**
 *
 * @author AL-SABA
 */
public class govt_home extends javax.swing.JFrame {

    /**
     * Creates new form govt_home
     */
    public govt_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        bg02 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        govt_panel_01 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        school_name = new javax.swing.JTextField();
        school_id = new javax.swing.JTextField();
        school_thana = new javax.swing.JTextField();
        school_district = new javax.swing.JTextField();
        school_village = new javax.swing.JTextField();
        school_password = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        clean_1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        govt_examination = new javax.swing.JTextField();
        govt_year = new javax.swing.JTextField();
        govt_studentid = new javax.swing.JTextField();
        govt_res_4 = new javax.swing.JTextField();
        govt_res_2 = new javax.swing.JTextField();
        govt_res_3 = new javax.swing.JTextField();
        govt_res_1 = new javax.swing.JTextField();
        govt_res_gpa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        govt_res_browes = new javax.swing.JButton();
        clean_2 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        govt_sub_4 = new javax.swing.JTextField();
        govt_sub_1 = new javax.swing.JTextField();
        govt_sub_2 = new javax.swing.JTextField();
        govt_sub_3 = new javax.swing.JTextField();
        govt_board = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bg01 = new javax.swing.JLabel();
        home_button_02 = new javax.swing.JLabel();
        registation_button_02 = new javax.swing.JLabel();
        bordresult_button_02 = new javax.swing.JLabel();
        notic_button_02 = new javax.swing.JLabel();
        logout_button_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/govt bg.png"))); // NOI18N
        bg02.setToolTipText("");
        jPanel6.add(bg02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 70));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 01.png"))); // NOI18N
        jToggleButton1.setToolTipText("");
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseExited(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, -1, -1));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 01.png"))); // NOI18N
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseExited(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 01.png"))); // NOI18N
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseExited(evt);
            }
        });
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 01.png"))); // NOI18N
        jToggleButton4.setSelected(true);
        jToggleButton4.setBorderPainted(false);
        jToggleButton4.setContentAreaFilled(false);
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseExited(evt);
            }
        });
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 01.png"))); // NOI18N
        jToggleButton5.setContentAreaFilled(false);
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseExited(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(232, 230, 217));
        jPanel7.setForeground(new java.awt.Color(232, 230, 217));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 270, 310));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo_2.png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 640));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 640));

        govt_panel_01.addTab("tab1", jPanel1);

        jPanel9.setBackground(new java.awt.Color(232, 230, 217));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        school_name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 90, 170, 40));

        school_id.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 168, 170, 40));

        school_thana.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_thana, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 320, 170, 40));

        school_district.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 397, 170, 40));

        school_village.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_village, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 321, 170, 40));

        school_password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel9.add(school_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 397, 170, 40));

        save.setBackground(new java.awt.Color(232, 230, 217));
        save.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(51, 51, 51));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel9.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 508, -1, -1));

        clean_1.setBackground(new java.awt.Color(232, 230, 217));
        clean_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        clean_1.setForeground(new java.awt.Color(51, 51, 51));
        clean_1.setText("Clear");
        clean_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_1ActionPerformed(evt);
            }
        });
        jPanel9.add(clean_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 508, -1, -1));

        jPanel10.setBackground(new java.awt.Color(232, 230, 217));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Password:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 150, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/school reg.png"))); // NOI18N
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 560));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        govt_panel_01.addTab("tab2", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(232, 230, 217));
        jPanel8.setForeground(new java.awt.Color(232, 230, 217));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        govt_examination.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel8.add(govt_examination, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 113, 170, 40));

        govt_year.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel8.add(govt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 189, 170, 40));

        govt_studentid.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel8.add(govt_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 191, 170, 40));
        jPanel8.add(govt_res_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 90, 30));
        jPanel8.add(govt_res_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 90, 30));
        jPanel8.add(govt_res_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 90, 30));
        jPanel8.add(govt_res_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 90, 30));
        jPanel8.add(govt_res_gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 90, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Edit");
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        govt_res_browes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        govt_res_browes.setText("Browse");
        jPanel8.add(govt_res_browes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        clean_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clean_2.setText("Clean");
        clean_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_2ActionPerformed(evt);
            }
        });
        jPanel8.add(clean_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        save1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save1.setText("Save");
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1MouseClicked(evt);
            }
        });
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel8.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel8.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 220, 110));

        govt_sub_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(govt_sub_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 150, 30));

        govt_sub_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(govt_sub_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 30));

        govt_sub_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(govt_sub_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 150, 30));

        govt_sub_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(govt_sub_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 150, 30));

        govt_board.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select exam--", "Dhaka", "Chittagong", "Rajshahi", "Khulna", "Barisal", "Sylhet", "Comilla", "Jessore", "Dinajpur", "Madrasah", "Technical" }));
        jPanel8.add(govt_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 115, 170, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("GPA");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mark");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bord reg.png"))); // NOI18N
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 630));

        govt_panel_01.addTab("tab3", jPanel3);

        jPanel5.setBackground(new java.awt.Color(232, 230, 217));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(232, 230, 217));
        jComboBox1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergency Contract", "Doctor  16263", "Fire Service  102", "Police  999", " " }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 220, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/note.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, -1, 587));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        govt_panel_01.addTab("tab4", jPanel4);

        jPanel6.add(govt_panel_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 830, 630));

        bg01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/govt home.png"))); // NOI18N
        jPanel6.add(bg01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        home_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 02.png"))); // NOI18N
        jPanel6.add(home_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        registation_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 02.png"))); // NOI18N
        jPanel6.add(registation_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, 40));

        bordresult_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 02.png"))); // NOI18N
        jPanel6.add(bordresult_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 337, -1, 30));

        notic_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 02.png"))); // NOI18N
        jPanel6.add(notic_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        logout_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 02.png"))); // NOI18N
        jPanel6.add(logout_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jToggleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseEntered
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 02.png")));
    }//GEN-LAST:event_jToggleButton1MouseEntered
    private void jToggleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseExited
      jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 01.png")));
    }//GEN-LAST:event_jToggleButton1MouseExited
    private void jToggleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseEntered
      jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 02.png")));
    }//GEN-LAST:event_jToggleButton5MouseEntered
    private void jToggleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseExited
      jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 01.png")));
    }//GEN-LAST:event_jToggleButton5MouseExited
    private void jToggleButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseEntered
      jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 02.png")));
    }//GEN-LAST:event_jToggleButton2MouseEntered
    private void jToggleButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseExited
      jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 01.png")));
    }//GEN-LAST:event_jToggleButton2MouseExited
    private void jToggleButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseEntered
      jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 02.png")));
    }//GEN-LAST:event_jToggleButton4MouseEntered
    private void jToggleButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseExited
      jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 01.png")));
    }//GEN-LAST:event_jToggleButton4MouseExited
    private void jToggleButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseEntered
      jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 02.png")));
    }//GEN-LAST:event_jToggleButton3MouseEntered
    private void jToggleButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseExited
      jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 01.png")));
    }//GEN-LAST:event_jToggleButton3MouseExited
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        new govt_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
       govt_panel_01.setSelectedIndex(1);
    }//GEN-LAST:event_jToggleButton5ActionPerformed
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        govt_panel_01.setSelectedIndex(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        govt_panel_01.setSelectedIndex(2);
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        govt_panel_01.setSelectedIndex(3);
    }//GEN-LAST:event_jToggleButton4ActionPerformed
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        String s_name      =  school_name.getText();
        String s_id        =  school_id.getText();
        String s_thana     =  school_thana.getText();
        String s_district  =  school_district.getText();
        String s_village   =  school_village.getText();
        String s_password  =  school_password.getText();

        
        String sql;
            sql = ("INSERT INTO registration (school_name,school_id,school_village,school_thana,school_district,school_pass) VALUES ('"+s_name+"','"+s_id+"' ,'"+s_village+"','"+s_thana+"', '"+s_district+"','"+s_password+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_saveActionPerformed

    
    
    private void clean_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_1ActionPerformed
         school_name.setText("");
         school_id.setText("");
         school_thana.setText("");
         school_district.setText("");
         school_village.setText("");
         school_password.setText("");
    }//GEN-LAST:event_clean_1ActionPerformed
    private void clean_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_2ActionPerformed
        govt_examination.setText("");
        govt_year.setText("");
        govt_board.setSelectedIndex(0);
        govt_studentid.setText("");
        govt_sub_1.setText("");
        govt_sub_2.setText("");
        govt_sub_3.setText("");
        govt_sub_4.setText("");
        govt_res_1.setText("");
        govt_res_2.setText("");
        govt_res_3.setText("");
        govt_res_4.setText("");
        govt_res_gpa.setText("");
    }//GEN-LAST:event_clean_2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
            String u1 = govt_studentid.getText();
            String u2 = govt_examination.getText();
            String u3 = govt_year.getText();
            String u4 = (String)govt_board.getSelectedItem();

            String sql = "SELECT * FROM board_admission WHERE s_id=? and s_exam=? and s_year=? and s_board=?";
            try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, u1);
                pstmt.setString(2, u2);
                pstmt.setString(3, u3);
                pstmt.setString(4, u4);
                
                
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                         JOptionPane.showMessageDialog(this, "Found your ID");
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Found your ID");
                  }
                }
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        String sub_1      =  govt_sub_1.getText();
        String sub_2      =  govt_sub_2.getText();
        String sub_3      =  govt_sub_3.getText();
        String sub_4      =  govt_sub_4.getText();
        String res_1      =  govt_res_1.getText();
        String res_2      =  govt_res_2.getText();
        String res_3      =  govt_res_3.getText();
        String res_4      =  govt_res_4.getText();
        String res_gpa    =  govt_res_gpa.getText();
        String st_id    =  govt_studentid.getText();
        
        //String res_browes =  govt_res_browes.getText();
        
        String sql;
            sql = ("INSERT INTO boord_result(b_sub_name01, b_sub_name02, b_sub_name03, b_sub_name04, b_sub_result01, b_sub_result02, b_sub_result03, b_sub_result04, b_gpa,st_id) VALUES ('"+sub_1+"','"+sub_2+"','"+sub_3+"','"+sub_4+"','"+res_1+"','"+res_2+"','"+res_3+"','"+res_4+"','"+res_gpa+"','"+st_id+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } 
    }//GEN-LAST:event_save1ActionPerformed

    private void save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_save1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new govt_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg01;
    private javax.swing.JLabel bg02;
    private javax.swing.JLabel bordresult_button_02;
    private javax.swing.JButton clean_1;
    private javax.swing.JButton clean_2;
    private javax.swing.JComboBox<String> govt_board;
    private javax.swing.JTextField govt_examination;
    private javax.swing.JTabbedPane govt_panel_01;
    private javax.swing.JTextField govt_res_1;
    private javax.swing.JTextField govt_res_2;
    private javax.swing.JTextField govt_res_3;
    private javax.swing.JTextField govt_res_4;
    private javax.swing.JButton govt_res_browes;
    private javax.swing.JTextField govt_res_gpa;
    private javax.swing.JTextField govt_studentid;
    private javax.swing.JTextField govt_sub_1;
    private javax.swing.JTextField govt_sub_2;
    private javax.swing.JTextField govt_sub_3;
    private javax.swing.JTextField govt_sub_4;
    private javax.swing.JTextField govt_year;
    private javax.swing.JLabel home_button_02;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JLabel logout_button_02;
    private javax.swing.JLabel notic_button_02;
    private javax.swing.JLabel registation_button_02;
    private javax.swing.JButton save;
    public javax.swing.JButton save1;
    private javax.swing.JTextField school_district;
    private javax.swing.JTextField school_id;
    private javax.swing.JTextField school_name;
    private javax.swing.JTextField school_password;
    private javax.swing.JTextField school_thana;
    private javax.swing.JTextField school_village;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
