/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.student_login;
import java.awt.HeadlessException;
import java.lang.System.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
;
/**
 *
 * @author AL-SABA
 */
public class student_home extends javax.swing.JFrame {

    private PreparedStatement pst;

    /**
     * Creates new form student_home
     */
    public student_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        teacher_panal = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        classes = new javax.swing.JComboBox<>();
        t5 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        serch = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bg1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        br1 = new javax.swing.JTextField();
        br2 = new javax.swing.JTextField();
        br3 = new javax.swing.JTextField();
        br4 = new javax.swing.JTextField();
        br5 = new javax.swing.JTextField();
        sr1 = new javax.swing.JButton();
        id_03 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1210, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(181, 226, 123));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Job Circular");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/stude-job.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 740, 390));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        teacher_panal.addTab("tab1", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        classes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Class--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel5.add(classes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 189, 40));
        jPanel5.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 162, 36));
        jPanel5.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 189, 162, 36));
        jPanel5.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 231, 162, 36));
        jPanel5.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 279, 162, 36));
        jPanel5.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 327, 162, 36));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 162, 36));
        jPanel5.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 162, 36));
        jPanel5.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 162, 36));
        jPanel5.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 162, 36));
        jPanel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 162, 36));

        serch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        serch.setText("Search");
        serch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchActionPerformed(evt);
            }
        });
        jPanel5.add(serch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("School Result");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, -1));

        teacher_panal.addTab("tab2", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 100, -1));

        b2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, -1));

        b5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, -1));

        b4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, -1));

        b1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, -1));

        b3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));

        br1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(br1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, -1));

        br2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(br2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 100, -1));

        br3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(br3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, -1));

        br4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(br4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, -1));

        br5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(br5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, -1));

        sr1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sr1.setText("Search");
        sr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1ActionPerformed(evt);
            }
        });
        jPanel6.add(sr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        id_03.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_03.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel6.add(id_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 100, 40));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("GPA");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setText("Subjects");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setText("Marks");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        teacher_panal.addTab("tab3", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 440, 630));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        teacher_panal.addTab("tab4", jPanel7);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        teacher_panal.addTab("tab5", jPanel8);

        jPanel1.add(teacher_panal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -40, 830, 730));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(236, 236, 236));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton2.setText("Board Result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(236, 236, 236));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton5.setBackground(new java.awt.Color(236, 236, 236));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton5.setText("Certificate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton6.setBackground(new java.awt.Color(236, 236, 236));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton6.setText("Routine");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jButton4.setBackground(new java.awt.Color(236, 236, 236));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jButton7.setBackground(new java.awt.Color(236, 236, 236));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jButton7.setText("Results");
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/studennt home.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 810));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        teacher_panal.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       teacher_panal.setSelectedIndex(1);
    }//GEN-LAST:event_jButton7ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        teacher_panal.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        teacher_panal.setSelectedIndex(3);
    }//GEN-LAST:event_jButton5ActionPerformed
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       teacher_panal.setSelectedIndex(4);
    }//GEN-LAST:event_jButton6ActionPerformed
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new student_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void serchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchActionPerformed
   try {
        Class.forName("com.mysql.cj.jdbc.Driver");
    } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Database Driver not found!");
        return;
    }

    if (classes.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please select a class ID.");
        return;
    }

    String s_class = (String) classes.getSelectedItem();
    String sql = "SELECT id, s_id, s_class, s_sub_name01, s_sub_name02, s_sub_name03, s_sub_res01, s_sub_res02, s_sub_res03, s_total_result FROM school_result WHERE s_class=?";
    
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {
        
        pst.setString(1, s_class);
        try (ResultSet rs1 = pst.executeQuery()) {
            if (!rs1.next()) {
                JOptionPane.showMessageDialog(this, "Sorry, Record Not Found");
                clearFields();
            } else {
                setFields(rs1);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
       // For debugging
    }
}

private void clearFields() {
    t1.setText("");
    t2.setText("");
    t3.setText("");
    m1.setText("");
    m2.setText("");
    m3.setText("");
}

private void setFields(ResultSet rs) throws SQLException {
    t1.setText(rs.getString("s_sub_name01"));
    t2.setText(rs.getString("s_sub_name02"));
    t3.setText(rs.getString("s_sub_name03"));
    m1.setText(rs.getString("s_sub_res01"));
    m2.setText(rs.getString("s_sub_res02"));
    m3.setText(rs.getString("s_sub_res03"));
    }//GEN-LAST:event_serchActionPerformed

    private void sr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1ActionPerformed
   try {
        Class.forName("com.mysql.cj.jdbc.Driver");
    } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Database Driver not found!");
        return;
    }

    if (id_03.getText() == null) {
        JOptionPane.showMessageDialog(this, "Please select a student ID.");
        return;
    }

    String st_id = id_03.getText();
    String sql = "SELECT id, b_sub_name01, b_sub_name02, b_sub_name03, b_sub_name04, b_sub_result01, b_sub_result02, b_sub_result03, b_sub_result04, b_gpa, st_id FROM boord_result WHERE st_id=?";
    
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {
        
        pst.setString(1, st_id);
        try (ResultSet rs1 = pst.executeQuery()) {
            if (!rs1.next()) {
                JOptionPane.showMessageDialog(this, "Sorry, Record Not Found");
                clearFields();
            } else {
                setFields(rs1);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
       // For debugging
    }
}

private void clearfields() {
b1.setText("");
b2.setText("");
b3.setText("");
b4.setText("");

br1.setText("");
br2.setText("");
br3.setText("");
br4.setText("");
bg1.setText("");
}

private void setfields(ResultSet rs) throws SQLException {
b1.setText(rs.getString("b_sub_name01"));
b2.setText(rs.getString("b_sub_name02"));
b3.setText(rs.getString("b_sub_name03"));
b4.setText(rs.getString("b_sub_res01"));

br1.setText(rs.getString("b_sub_result01"));
br2.setText(rs.getString("b_sub_result02"));
br3.setText(rs.getString("b_sub_result03"));
br4.setText(rs.getString("b_sub_result04"));
bg1.setText(rs.getString("b_total_result"));
    }//GEN-LAST:event_sr1ActionPerformed

    /* /**
    * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new student_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField bg1;
    private javax.swing.JTextField br1;
    private javax.swing.JTextField br2;
    private javax.swing.JTextField br3;
    private javax.swing.JTextField br4;
    private javax.swing.JTextField br5;
    private javax.swing.JComboBox<String> classes;
    private javax.swing.JTextField id_03;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JButton serch;
    private javax.swing.JButton sr1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTabbedPane teacher_panal;
    // End of variables declaration//GEN-END:variables
}
