/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.teacher_login;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author AL-SABA
 */
public class teacher_home extends javax.swing.JFrame {

    /**
     * Creates new form teacher_home
     */
    public teacher_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        schoolresult = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        admition = new javax.swing.JButton();
        routine = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        teacher_panel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nsid_mother_district = new javax.swing.JTextField();
        nsid_mother_thana = new javax.swing.JTextField();
        nsid_father_district = new javax.swing.JTextField();
        nsid_father_thana = new javax.swing.JTextField();
        nsid_birthno = new javax.swing.JTextField();
        nsid_dateofbirth = new javax.swing.JTextField();
        nsid_mother_nidno = new javax.swing.JTextField();
        nsid_mother_name = new javax.swing.JTextField();
        nsid_father_nidno = new javax.swing.JTextField();
        nsid_father_name = new javax.swing.JTextField();
        nsid_id = new javax.swing.JTextField();
        nsid_name = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        clean_1 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        student_id_01 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        clean_2 = new javax.swing.JButton();
        std_sub_1 = new javax.swing.JComboBox<>();
        std_sub_2 = new javax.swing.JComboBox<>();
        std_sub_3 = new javax.swing.JComboBox<>();
        std_sub_res1 = new javax.swing.JTextField();
        std_sub_res2 = new javax.swing.JTextField();
        std_sub_res3 = new javax.swing.JTextField();
        std_sub_restotal = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        std_class = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        student_id_02 = new javax.swing.JTextField();
        student_name_01 = new javax.swing.JTextField();
        student_class_01 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        student_year_01 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        clean_3 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        student_id_03 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        student_name_02 = new javax.swing.JTextField();
        student_year_02 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        clean_4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        student_class_02 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        board = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        bord1 = new javax.swing.JComboBox<>();
        bord2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        home_button_02 = new javax.swing.JLabel();
        schoolresult_02 = new javax.swing.JLabel();
        registation_02 = new javax.swing.JLabel();
        admission_02 = new javax.swing.JLabel();
        routine_02 = new javax.swing.JLabel();
        logout_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tc bg.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 05.png"))); // NOI18N
        home.setContentAreaFilled(false);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        schoolresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 01.png"))); // NOI18N
        schoolresult.setContentAreaFilled(false);
        schoolresult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schoolresultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schoolresultMouseExited(evt);
            }
        });
        schoolresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolresultActionPerformed(evt);
            }
        });
        getContentPane().add(schoolresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 03.png"))); // NOI18N
        registration.setContentAreaFilled(false);
        registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrationMouseExited(evt);
            }
        });
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        getContentPane().add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        admition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 01.png"))); // NOI18N
        admition.setContentAreaFilled(false);
        admition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admitionMouseExited(evt);
            }
        });
        admition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitionActionPerformed(evt);
            }
        });
        getContentPane().add(admition, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        routine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 03.png"))); // NOI18N
        routine.setContentAreaFilled(false);
        routine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                routineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                routineMouseExited(evt);
            }
        });
        routine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routineActionPerformed(evt);
            }
        });
        getContentPane().add(routine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 05.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 52, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tournament");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo_te.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 720, 340));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/notic st.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 795, 275));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 780));

        teacher_panel.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nsid_mother_district.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_mother_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 180, 40));

        nsid_mother_thana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_mother_thana, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 180, 40));

        nsid_father_district.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_father_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 180, 40));

        nsid_father_thana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_father_thana, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 180, 40));

        nsid_birthno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_birthno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 180, 40));

        nsid_dateofbirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 180, 40));

        nsid_mother_nidno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_mother_nidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 569, 180, 40));

        nsid_mother_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_mother_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 488, 180, 40));

        nsid_father_nidno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_father_nidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 180, 40));

        nsid_father_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 180, 40));

        nsid_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nsid_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(nsid_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 172, 180, 40));

        nsid_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(nsid_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 91, 180, 40));

        jButton16.setBackground(new java.awt.Color(61, 52, 139));
        jButton16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Save");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        clean_1.setBackground(new java.awt.Color(61, 52, 139));
        clean_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        clean_1.setForeground(new java.awt.Color(255, 255, 255));
        clean_1.setText("Clean");
        clean_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_1ActionPerformed(evt);
            }
        });
        jPanel4.add(clean_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        jButton18.setBackground(new java.awt.Color(61, 52, 139));
        jButton18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Edit");
        jPanel4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/nsid reg.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel9.setBackground(new java.awt.Color(61, 52, 139));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 680));

        teacher_panel.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(61, 52, 139));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 118, 63, 45));

        student_id_01.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(student_id_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 132, 138, -1));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setText("Save");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 359, -1, -1));

        clean_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clean_2.setText("Clean");
        clean_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_2ActionPerformed(evt);
            }
        });
        jPanel5.add(clean_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 359, -1, -1));

        std_sub_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selection--", "Bangla", "English", "Math" }));
        jPanel5.add(std_sub_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 181, 138, 33));

        std_sub_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selection--", "Bangla", "English", "Math" }));
        jPanel5.add(std_sub_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 138, 33));

        std_sub_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selection--", "Bangla", "English", "Math" }));
        jPanel5.add(std_sub_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 259, 138, 33));
        jPanel5.add(std_sub_res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 181, 111, 33));
        jPanel5.add(std_sub_res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 220, 111, 33));
        jPanel5.add(std_sub_res3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 259, 111, 33));
        jPanel5.add(std_sub_restotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 298, 111, 33));

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton14.setText("Edit");
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 359, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Result");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 55, -1, -1));

        std_class.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(std_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 138, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student ID:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 120, 106, 45));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 298, 62, 45));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 90, -1));

        teacher_panel.addTab("tab3", jPanel5);

        jPanel7.setBackground(new java.awt.Color(61, 52, 139));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/routine  teacher.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 800, 600));

        teacher_panel.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(61, 52, 139));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student ID:");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class:");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student Name:");

        student_id_02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        student_name_01.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        student_class_01.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Year:");

        student_year_01.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton12.setText("Save");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        clean_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clean_3.setText("Clean");
        clean_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_3ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton15.setText("Edit");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("School Admission");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Board Admission");

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Student ID:");

        student_id_03.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Student Name:");

        student_name_02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        student_year_02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Year:");

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton19.setText("Save");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton20.setText("Edit");

        clean_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clean_4.setText("Clean");
        clean_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Examinatio:");

        student_class_02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        board.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Board:");

        bord1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select exam--", "Dhaka", "Chittagong", "Rajshahi", "Khulna", "Barisal", "Sylhet", "Comilla", "Jessore", "Dinajpur", "Madrasah", "Technical" }));

        bord2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select exam--", "JSC", "SSC", "HSC", "BSC" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(student_name_01, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(student_class_01, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(student_id_02, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(student_year_01, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(student_id_03, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(jButton9))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(student_name_02, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel19))
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(bord2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22)))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(student_year_02, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bord1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jButton19)
                                                .addGap(46, 46, 46)
                                                .addComponent(jButton20))
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(clean_4)
                                                .addGap(177, 177, 177)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(student_class_02, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(jButton12)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButton15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clean_3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(189, 189, 189)
                                    .addComponent(jLabel16)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel9))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_id_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_name_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_year_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_class_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton15)
                    .addComponent(clean_3))
                .addGap(66, 66, 66)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_id_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(student_name_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bord2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(student_year_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bord1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(clean_4)))
                .addGap(18, 18, 18)
                .addComponent(student_class_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        teacher_panel.addTab("tab5", jPanel8);

        getContentPane().add(teacher_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 750, 690));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/teacher home.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 710));

        home_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 06.png"))); // NOI18N
        getContentPane().add(home_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        schoolresult_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 02.png"))); // NOI18N
        getContentPane().add(schoolresult_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        registation_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 04.png"))); // NOI18N
        getContentPane().add(registation_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        admission_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 02.png"))); // NOI18N
        getContentPane().add(admission_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        routine_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 04.png"))); // NOI18N
        routine_02.setToolTipText("");
        getContentPane().add(routine_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        logout_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 06.png"))); // NOI18N
        getContentPane().add(logout_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
       home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 06.png")));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
       home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 05.png")));
    }//GEN-LAST:event_homeMouseExited

    private void schoolresultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolresultMouseEntered
        schoolresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 02.png")));
    }//GEN-LAST:event_schoolresultMouseEntered

    private void schoolresultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolresultMouseExited
        schoolresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 01.png")));
    }//GEN-LAST:event_schoolresultMouseExited
    private void registrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseEntered
       registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 04.png")));
    }//GEN-LAST:event_registrationMouseEntered
    private void registrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseExited
       registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 03.png")));
    }//GEN-LAST:event_registrationMouseExited
    private void admitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitionMouseEntered
        admition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 02.png")));
    }//GEN-LAST:event_admitionMouseEntered
    private void admitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitionMouseExited
        admition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 01.png")));
    }//GEN-LAST:event_admitionMouseExited
    private void routineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseEntered
        routine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 04.png")));
    }//GEN-LAST:event_routineMouseEntered
    private void routineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseExited
        routine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 03.png")));
    }//GEN-LAST:event_routineMouseExited
    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 06.png")));
    }//GEN-LAST:event_jButton6MouseEntered
    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 05.png")));
    }//GEN-LAST:event_jButton6MouseExited
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new teacher_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        teacher_panel.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed
    private void schoolresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolresultActionPerformed
        teacher_panel.setSelectedIndex(2);
    }//GEN-LAST:event_schoolresultActionPerformed
    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        teacher_panel.setSelectedIndex(1);
    }//GEN-LAST:event_registrationActionPerformed
    private void admitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitionActionPerformed
       teacher_panel.setSelectedIndex(4);
    }//GEN-LAST:event_admitionActionPerformed
    private void routineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routineActionPerformed
        teacher_panel.setSelectedIndex(3);
    }//GEN-LAST:event_routineActionPerformed

    private void clean_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_1ActionPerformed
        nsid_name.setText("");
        nsid_id.setText("");
        nsid_dateofbirth.setText("");
        nsid_birthno.setText("");
        nsid_father_name.setText("");
        nsid_father_thana.setText("");
        nsid_father_district.setText("");
        nsid_father_nidno.setText("");
        nsid_mother_name.setText("");
        nsid_mother_thana.setText("");
        nsid_mother_district.setText("");
        nsid_mother_nidno.setText("");
    }//GEN-LAST:event_clean_1ActionPerformed
    private void clean_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_2ActionPerformed
        student_id_01.setText("");
        std_class.setText("");
        std_sub_1.setSelectedIndex(0);
        std_sub_2.setSelectedIndex(0);
        std_sub_3.setSelectedIndex(0);
        std_sub_res1.setText("");
        std_sub_res2.setText("");
        std_sub_res3.setText("");
        std_sub_restotal.setText("");
    }//GEN-LAST:event_clean_2ActionPerformed
    private void clean_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_3ActionPerformed
        student_id_02.setText("");
        student_class_01.setText("");
        student_name_01.setText("");
        student_year_01.setText("");      
    }//GEN-LAST:event_clean_3ActionPerformed
    private void clean_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_4ActionPerformed
        student_id_03.setText("");
        student_class_02.setText("");
        student_name_02.setText("");
        student_year_02.setText("");
    }//GEN-LAST:event_clean_4ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        
        String s_1    =  nsid_name.getText();
        String s_2    =  nsid_id.getText();
        String s_3    =  nsid_dateofbirth.getText();
        String s_4    =  nsid_birthno.getText();
        String s_5    =  nsid_father_name.getText();
        String s_6    =  nsid_father_nidno.getText();
        String s_7    =  nsid_father_thana.getText();
        String s_8    =  nsid_father_district.getText();
        String s_9    =  nsid_mother_name.getText();
        String s_10   = nsid_mother_nidno.getText();
        String s_11   =  nsid_mother_thana.getText();
        String s_12   =  nsid_mother_district.getText();
        
        String sql;
            sql = ("INSERT INTO nsid_registration (student_name, student_id, date_of_birth, birth_day_no, father_name, father_nid, father_thana, father_district, mother_name, mother_nid, mother_thana, mother_district) VALUES ('"+s_1+"','"+s_2+"' ,'"+s_3+"','"+s_4+"', '"+s_5+"','"+s_6+"','"+s_7+"','"+s_8+"','"+s_9+"','"+s_10+"','"+s_11+"','"+s_12+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
            String u1 = student_id_01.getText();
            String u2 = std_class.getText();
           
            String sql = "SELECT * FROM school_admission WHERE student_id=? and s_class=?";
            try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, u1);
                pstmt.setString(2, u2);
                              
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                         JOptionPane.showMessageDialog(this, "ID Is Found");
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Found your ID");
                  }
                }
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        String s_id     =  student_id_02.getText();
        String s_cls    =  student_class_01.getText();
        String s_name   =  student_name_01.getText();
        String s_year   =  student_year_01.getText();

        String sql;
            sql = ("INSERT INTO school_admission(student_id, s_class, s_name, s_year) VALUES ('"+s_id+"','"+s_cls+"' ,'"+s_name+"','"+s_year+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
            String user = student_id_02.getText();
            
            String sql = "SELECT * FROM nsid_registration WHERE student_id=?";
            try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, user);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                         JOptionPane.showMessageDialog(this, "Found your ID");
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Found your ID");
                        student_id_02.setText("");
                   }
                }
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
              try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
            String user = student_id_03.getText();
            
            String sql = "SELECT * FROM nsid_registration WHERE student_id=?";
            try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, user);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                         JOptionPane.showMessageDialog(this, "Found your ID");
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Found your ID");
                        student_id_02.setText("");
                   }
                }
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        String st_id     =  student_id_03.getText();
        String s_cls    =  (String)bord2.getSelectedItem();
        String s_name   =  student_name_02.getText();
        String s_year   =  student_year_02.getText();
        String s_board   =  (String)bord1.getSelectedItem();
        

        String sql;
            sql = ("INSERT INTO board_admission( s_id, s_name, s_exam, s_year, s_board) VALUES ('"+st_id+"','"+s_name+"' ,'"+s_cls+"','"+s_year+"','"+s_board+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } 
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
        Statement statement=con.createStatement();
        
        String s_1    =  student_id_01.getText();
        String s_2    =  std_class.getText();
        String s_3    =  (String)std_sub_1.getSelectedItem();
        String s_4    =  (String)std_sub_2.getSelectedItem();
        String s_5    =  (String)std_sub_3.getSelectedItem();
        String s_6    =  std_sub_res1.getText();
        String s_7    =  std_sub_res2.getText();
        String s_8    =  std_sub_res3.getText();
        
        String s_9    =  std_sub_restotal.getText();
                
        String sql;
            sql = ("INSERT INTO school_result(s_id, s_class, s_sub_name01, s_sub_name02, s_sub_name03, s_sub_res01, s_sub_res02, s_sub_res03, s_total_result) VALUES ('"+s_1+"','"+s_2+"' ,'"+s_3+"','"+s_4+"', '"+s_5+"','"+s_6+"','"+s_7+"','"+s_8+"','"+s_9+"')");
            statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Save Data");
        }}
        catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new teacher_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admission_02;
    private javax.swing.JButton admition;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField board;
    private javax.swing.JComboBox<String> bord1;
    private javax.swing.JComboBox<String> bord2;
    private javax.swing.JButton clean_1;
    private javax.swing.JButton clean_2;
    private javax.swing.JButton clean_3;
    private javax.swing.JButton clean_4;
    private javax.swing.JButton home;
    private javax.swing.JLabel home_button_02;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout_02;
    private javax.swing.JTextField nsid_birthno;
    private javax.swing.JTextField nsid_dateofbirth;
    private javax.swing.JTextField nsid_father_district;
    private javax.swing.JTextField nsid_father_name;
    private javax.swing.JTextField nsid_father_nidno;
    private javax.swing.JTextField nsid_father_thana;
    private javax.swing.JTextField nsid_id;
    private javax.swing.JTextField nsid_mother_district;
    private javax.swing.JTextField nsid_mother_name;
    private javax.swing.JTextField nsid_mother_nidno;
    private javax.swing.JTextField nsid_mother_thana;
    private javax.swing.JTextField nsid_name;
    private javax.swing.JLabel registation_02;
    private javax.swing.JButton registration;
    private javax.swing.JButton routine;
    private javax.swing.JLabel routine_02;
    private javax.swing.JButton schoolresult;
    private javax.swing.JLabel schoolresult_02;
    private javax.swing.JTextField std_class;
    private javax.swing.JComboBox<String> std_sub_1;
    private javax.swing.JComboBox<String> std_sub_2;
    private javax.swing.JComboBox<String> std_sub_3;
    private javax.swing.JTextField std_sub_res1;
    private javax.swing.JTextField std_sub_res2;
    private javax.swing.JTextField std_sub_res3;
    private javax.swing.JTextField std_sub_restotal;
    private javax.swing.JTextField student_class_01;
    private javax.swing.JTextField student_class_02;
    private javax.swing.JTextField student_id_01;
    private javax.swing.JTextField student_id_02;
    private javax.swing.JTextField student_id_03;
    private javax.swing.JTextField student_name_01;
    private javax.swing.JTextField student_name_02;
    private javax.swing.JTextField student_year_01;
    private javax.swing.JTextField student_year_02;
    private javax.swing.JTabbedPane teacher_panel;
    // End of variables declaration//GEN-END:variables
}
