/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Log_IN;

import home.student_home;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AL-SABA
 */
public class student_login extends javax.swing.JFrame {

    /**
     * Creates new form student_login
     */
    public student_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_id = new javax.swing.JTextField();
        user_pass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        icon01 = new javax.swing.JLabel();
        show_password = new javax.swing.JCheckBox();
        bg = new javax.swing.JLabel();
        login_button_02 = new javax.swing.JLabel();
        icon02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_id.setBackground(new java.awt.Color(245, 245, 245));
        user_id.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        user_id.setBorder(null);
        jPanel1.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 293, 290, 40));

        user_pass.setBackground(new java.awt.Color(245, 245, 245));
        user_pass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        user_pass.setBorder(null);
        jPanel1.add(user_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 280, 40));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 02.png"))); // NOI18N
        login.setContentAreaFilled(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 476, -1, -1));

        icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon02.png"))); // NOI18N
        icon01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon01MouseExited(evt);
            }
        });
        jPanel1.add(icon01, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        show_password.setText("Show Password");
        show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/student login.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        login_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 03.png"))); // NOI18N
        jPanel1.add(login_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, -1, -1));

        icon02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon03.png"))); // NOI18N
        jPanel1.add(icon02, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseEntered
         icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon03.png")));
    }//GEN-LAST:event_icon01MouseEntered

    private void icon01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseExited
        icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon02.png")));
    }//GEN-LAST:event_icon01MouseExited

    private void icon01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseClicked
        new Home_page_all_account().setVisible(true);
        dispose();
    }//GEN-LAST:event_icon01MouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 03.png")));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
       login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 02.png")));
    }//GEN-LAST:event_loginMouseExited

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nsid?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
            String user = user_id.getText();
            String pass = user_pass.getText();
            
            
            // Use PreparedStatement to prevent SQL injection
            String sql = "SELECT * FROM nsid_registration WHERE student_id=? AND student_id=?";
            try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, user);
                pstmt.setString(2, pass);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        new student_home().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Wrong username or password...");
                       user_id.setText("");
                       user_pass.setText("");
                    }
                }
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) { // Helps to identify errors
        // Helps to identify errors
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_loginActionPerformed

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed

    if (show_password.isSelected()) {
        user_pass.setEchoChar((char) 0); // Show password
    } else {
        user_pass.setEchoChar('*'); // Hide password
    }  
    }//GEN-LAST:event_show_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new student_login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel icon01;
    private javax.swing.JLabel icon02;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel login_button_02;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JTextField user_id;
    private javax.swing.JPasswordField user_pass;
    // End of variables declaration//GEN-END:variables
}
